// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogArgValueData } from "./CatalogArgValueData";

export type CatalogArgData = { name: string, value: CatalogArgValueData, };
