// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructuredTextData } from "./StructuredTextData";

export type CatalogArgValueData = { "kind": "text", "value": string } | { "kind": "bool", "value": boolean } | { "kind": "signed", "value": string } | { "kind": "unsigned", "value": string } | { "kind": "nested_text", "value": StructuredTextData } | { "kind": "unsupported" };
