// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCategoryData } from "./ErrorCategoryData";
import type { ErrorRetryAdviceData } from "./ErrorRetryAdviceData";
import type { StructuredTextData } from "./StructuredTextData";

export type ErrorData = { code: string, category: ErrorCategoryData, retry_advice: ErrorRetryAdviceData, user_text: StructuredTextData, diagnostic_text: StructuredTextData | null, };
