// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCategoryData = "invalid_input" | "not_found" | "conflict" | "permission_denied" | "unauthenticated" | "rate_limited" | "timeout" | "unavailable" | "external_dependency" | "internal";
