// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogArgData } from "./CatalogArgData";

export type StructuredTextData = { "kind": "catalog", code: string, args: Array<CatalogArgData>, } | { "kind": "freeform", text: string, };
